/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab7;

import javax.swing.JOptionPane;

/**
 *
 * @author Tai-E758
 */
public class NewCDDialog extends javax.swing.JFrame {

    public CDManager managerCD = new CDManager();

    /**
     * Creates new form NewCDDialog
     */
    public NewCDDialog(CDManager managerCD) {
        initComponents();
        this.managerCD = managerCD;
    }

    private NewCDDialog() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        collection = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        audio = new javax.swing.JRadioButton();
        video = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("CD ID");
        jLabel1.setPreferredSize(new java.awt.Dimension(125, 25));
        jPanel1.add(jLabel1);

        id.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        id.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(id);

        jLabel2.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("CD Title");
        jLabel2.setPreferredSize(new java.awt.Dimension(125, 25));
        jPanel2.add(jLabel2);

        title.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        title.setPreferredSize(new java.awt.Dimension(250, 25));
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        jPanel2.add(title);

        jLabel3.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("CD Collection");
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel3.add(jLabel3);

        collection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Game", "Movie", "Music" }));
        collection.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel3.add(collection);

        jLabel4.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("CD Type");
        jLabel4.setPreferredSize(new java.awt.Dimension(75, 25));
        jPanel3.add(jLabel4);

        audio.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        audio.setText("Audio");
        audio.setPreferredSize(new java.awt.Dimension(75, 25));
        audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioActionPerformed(evt);
            }
        });
        jPanel3.add(audio);

        video.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        video.setText("Video");
        video.setPreferredSize(new java.awt.Dimension(75, 25));
        video.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoActionPerformed(evt);
            }
        });
        jPanel3.add(video);

        jLabel5.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("CD Price");
        jLabel5.setPreferredSize(new java.awt.Dimension(125, 25));
        jPanel4.add(jLabel5);

        price.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        price.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel4.add(price);

        jLabel6.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("CD Year of Release");
        jLabel6.setPreferredSize(new java.awt.Dimension(125, 25));
        jPanel5.add(jLabel6);

        year.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        year.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel5.add(year);

        btnAdd.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(75, 25));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel6.add(btnAdd);

        btnClear.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(75, 25));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel6.add(btnClear);

        btnShowAll.setFont(new java.awt.Font("Windows 7 Segoe UI", 0, 12)); // NOI18N
        btnShowAll.setText("Show All");
        btnShowAll.setPreferredSize(new java.awt.Dimension(100, 25));
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });
        jPanel6.add(btnShowAll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void audioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audioActionPerformed

    private void videoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_videoActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (checkInfo()) {
            if (audio.isSelected()) {
                CDInformation cd1 = new CDInformation(id.getText(), title.getText(), collection.getSelectedItem().toString(), "Audio", Integer.parseInt(price.getText()), Integer.parseInt(year.getText()));
                if (managerCD.addCD(cd1) == true) {
                    JOptionPane.showMessageDialog(null, "CD Added Successfully", "Notification", JOptionPane.CLOSED_OPTION);
                } else {
                    JOptionPane.showMessageDialog(null, "CD Is Already In The List", "Notification", JOptionPane.ERROR_MESSAGE);
                }
            } else if (video.isSelected()) {
                CDInformation cd1 = new CDInformation(id.getText(), title.getText(), collection.getSelectedItem().toString(), "Video", Integer.parseInt(price.getText()), Integer.parseInt(year.getText()));
                if (managerCD.addCD(cd1) == true) {
                    JOptionPane.showMessageDialog(null, "CD Added Successfully", "Notification", JOptionPane.CLOSED_OPTION);
                } else {
                    JOptionPane.showMessageDialog(null, "CD Is Already In The List", "Notification", JOptionPane.ERROR_MESSAGE);
                }
            }
            Clear();
        } else {
            JOptionPane.showMessageDialog(null, "You Need To Enter All Information & Only Choose Audio Or Video", "Notification", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        managerCD.showAllCD();
    }//GEN-LAST:event_btnShowAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCDDialog().setVisible(true);
            }
        });
    }

    private boolean checkInfo() {
        return !(id.getText().isEmpty() || title.getText().isEmpty() || price.getText().isEmpty() || year.getText().isEmpty() || (audio.isSelected() && video.isSelected()) || (!audio.isSelected() && !video.isSelected()));
    }

    private void Clear() {
        id.setText("");
        title.setText("");
        audio.setSelected(false);
        video.setSelected(false);
        price.setText("");
        year.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton audio;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JComboBox<String> collection;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField price;
    private javax.swing.JTextField title;
    private javax.swing.JRadioButton video;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
